kind: pipeline
type: kubernetes
name: default

steps:
  - name: Create BOM
    image: node
    depends_on: ["clone"]
    environment:
      API_KEY:
        from_secret: dependency-track
    commands:
      - "pnpm dlx pnpm dlx @cyclonedx/cdxgen --api-key $API_KEY --server-url https://api-sbom.home.fa.gl --project-version $(git rev-parse --abbrev-ref HEAD)"
  - name: Build API
    image: plugins/kaniko
    depends_on: ["clone"]
    settings:
      username: boi
      password:
        from_secret: docker_pat
      registry: git.home.fa.gl
      repo: git.home.fa.gl/boi/item-tracker-api
      tags: latest
      dockerfile: Dockerfile
  - name: Build Frontend
    image: plugins/kaniko
    depends_on: ["clone"]
    settings:
      username: boi
      password:
        from_secret: docker_pat
      registry: git.home.fa.gl
      repo: git.home.fa.gl/boi/item-tracker-frontend
      tags: latest
      dockerfile: Dockerfile.web