FROM node:19-alpine as build

WORKDIR /build

COPY . ./

RUN mv pnpm-workspace.frontend.yaml pnpm-workspace.yaml && \
    corepack enable && corepack prepare pnpm@latest --activate && \
    pnpm i --frozen-lockfile && \
    pnpm frontend build && \
    mkdir /app && \
    cp packages/frontend/dist/* /app && \
    rm -rf /build

FROM nginx:stable-alpine as RUN
WORKDIR /app
COPY --from=build /app /usr/share/nginx/html
COPY deploy/ci/nginx-server.conf /etc/nginx/conf.d/server.conf

CMD ["nginx", "-g", "daemon off;"]
