apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: item-tracker-ingress
spec:
  routes:
  - kind: Rule
    match: Host(`track.home.fa.gl`) && PathPrefix(`/api`)
    services:
    - name: item-tracker-api
      port: 4000
  - kind: Rule
    match: Host(`track.home.fa.gl`)
    services:
    - name: item-tracker-frontend
      port: 80
